apiVersion: v1
kind: Service
metadata:
  name: loan-approval-service
spec:
  type: LoadBalancer
  selector:
    app: loan-approval-prediction
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000